language: r
sudo: required
cache: packages
dist: trusty
r: release
r_binary_packages:
    - devtools
r_github_packages:
    - r-lib/rcmdcheck
    - jimhester/lintr
    - jimhester/covr
script:
  - R -e 'r <- rcmdcheck::rcmdcheck(".", args = c("--no-manual")); l <- lintr::lint_package(".", linters = lintr::with_defaults(commas_linter = NULL, camel_case_linter = NULL, spaces_left_parentheses_linter = NULL, spaces_inside_linter, snake_case_linter)); print(l); devtools::test(); quit(save = "no", status = if (length(c(r$errors, r$warnings, l)) > 0) { 1 } else { 0 }, runLast = FALSE)'
after_success:
  - R -e 'library(covr); coveralls()'
env:
  - global:
    - CI=TRUE
    - LINTR_COMMENT_BOT=false
