language: r
sudo: required
cache:
  - r_packages
  - github_packages
dist: trusty
r:
    - oldrel
    - release
r_packages:
    - devtools
    - covr
r_github_packages:
    - r-lib/rcmdcheck
script:
  - R -e 'r <- rcmdcheck::rcmdcheck(".", args = c("--no-manual")); devtools::test(); quit(save = "no", status = if (length(c(r$errors, r$warnings)) > 0) { 1 } else { 0 }, runLast = FALSE)'
after_success:
  - R -e 'covr::codecov()'
env:
  - global:
    - CI=TRUE
    - LINTR_COMMENT_BOT=false
